# Site settings
title: AO-SUN|孙傲
description: Computer on, of course caffeine and a science of submission again.
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: /assets/images/favicon.png
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://ao-sun.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
#facebook: facebook
#twitter: twitter
github:  suntiansheng

#Additional Pages
about: about
contact: contact
#privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: ao-sun #github username
repo: ao-sun.github.io #github repository
branch: master #branch
relative_source: ../hanuman/ #source directory
destination: ../ao-sun.github.io/ #destination directory
production_url:  https://ao-sun.github.io/
source_url:  https://github.com/ao-sun/ao-sun.github.io.git #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
